services:
  django:
    build: ./backend/
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
  react:
    build: ./frontend/
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - django
