# Generated by Django 4.2.7 on 2023-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='last_usage',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='token',
            name='refresh_token',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='device_identity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
