# Generated by Django 4.2.7 on 2023-12-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=6000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('counter', models.IntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.message')),
                ('last_poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original_poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
