# Generated by Django 4.2.7 on 2023-12-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_message_thread_alter_thread_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='last_poster',
        ),
    ]
