# Generated by Django 4.2.7 on 2023-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_thread_last_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='listened',
            field=models.BooleanField(default=False),
        ),
    ]
