# Generated by Django 4.2.7 on 2023-12-21 14:47

from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_thread_listened'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=social.models.user_directory_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.message')),
            ],
        ),
    ]
