# Generated by Django 4.2.7 on 2023-12-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_messagefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefiles',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='social.message'),
        ),
    ]
