# Generated by Django 4.2.7 on 2023-12-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatethread',
            name='name',
        ),
    ]
