# Generated by Django 4.2.7 on 2023-12-21 14:47

from django.db import migrations, models
import django.db.models.deletion
import private.models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_remove_privatethread_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=private.models.user_directory_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.privatemessage')),
            ],
        ),
    ]
