# Generated by Django 4.2.7 on 2023-12-21 15:07

from django.db import migrations, models
import django.db.models.deletion
import private.models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_privatemessagefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=private.models.user_directory_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='private.privatemessage')),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateMessageFiles',
        ),
    ]
